version: 2
updates:

  - package-ecosystem: "npm"
    groups:
      prod-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 99

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "github-actions"
